version: "3.9"
services:
  web:
    image: registry.gitlab.com/flexoid/pivotal-slack-preview/main
    environment:
      - SLACK_TOKEN
      - SLACK_SIGNING_SECRET
      - PIVOTAL_TOKEN
    ports:
      - "127.0.0.1:19374:8080"
    restart: always
